### What is Image Embeddeding?

#### Most machine learning algorithms for classification, regression or clustering cannot work on images directly. To perform the analysis, we need to transform them into a more suitable representation.
>#### **Image embedding** is a **vector representation** of an image in which images with **similar motives have similar vector profiles.**

#### CNN, Neural networks expect the labels of classes in a dataset to be organized in a one-hot encoded manner: each row in the array contains zeros in all columns, except the column corresponding to a unique label, which is set to 1.

In [4]:
import pandas as pd
import numpy as np

In [9]:
labels = ['shoe', 'shirt', 'shoe', 'shirt', 'dress', 'dress', 'dress']

# The number of image categories
n_categories = 3

# The unique values of categories in the data
categories = np.array(["shirt", "dress", "shoe"])

# Initialize ohe_labels as all zeros
ohe_labels = np.zeros((len(labels), n_categories))

print(ohe_labels)
# Loop over the labels
for i in range(len(labels)):
    # Find the location of this label in the categories variable
    j = np.where(categories)
    
#     # Set the corresponding zero to one
#     ohe_labels[j] = 1

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(array([0, 1, 2]),)
(array([0, 1, 2]),)
(array([0, 1, 2]),)
(array([0, 1, 2]),)
(array([0, 1, 2]),)
(array([0, 1, 2]),)
(array([0, 1, 2]),)
